export enum VehiclesActionTypes {
    GET_VEHICLES = 'GET_VEHICLES',
    CREATE_VEHICLE = 'CREATE_VEHICLE',
    UPDATE_VEHICLE = 'UPDATE_VEHICLE',
    DELETE_VEHICLE = 'DELETE_VEHICLE',
    SET_CURRENT_VEHICLE = 'SET_CURRENT_VEHICLE',
}