export enum DriversActionTypes {
    GET_DRIVERS = 'GET_DRIVERS',
    CREATE_DRIVER = 'CREATE_DRIVER',
    UPDATE_DRIVER = 'UPDATE_DRIVER',
    DELETE_DRIVER = 'DELETE_DRIVER',
    SET_CURRENT_DRIVER = 'SET_CURRENT_DRIVER'
}